# Generated by Django 5.1.6 on 2025-02-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_country', models.CharField(max_length=64)),
                ('f1_racetrack', models.CharField(max_length=64)),
                ('f1_duration', models.IntegerField()),
                ('f1_price', models.IntegerField()),
            ],
        ),
    ]
