# Generated by Django 5.1.6 on 2025-02-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1ticketsapp', '0002_ticket_f1_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='f1_duration',
        ),
    ]
